/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.concesionaria.IGU.view;

import com.mycompany.concesionaria.Logica.Controladora;

/**
 *
 * @author veram
 */
public class Cargar extends javax.swing.JPanel {

    /**
     * Creates new form Cargar
     */
    public Cargar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        modeloL = new javax.swing.JLabel();
        marcaL = new javax.swing.JLabel();
        colorL = new javax.swing.JLabel();
        motorL = new javax.swing.JLabel();
        patenteL = new javax.swing.JLabel();
        cantPuertasL = new javax.swing.JLabel();
        marcaTxt = new javax.swing.JTextField();
        modeloTxt = new javax.swing.JTextField();
        colorTxt = new javax.swing.JTextField();
        motorTxt = new javax.swing.JTextField();
        patenteTxt = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        CantPuertasCB = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(779, 502));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cargar Auto");

        jSeparator1.setBackground(new java.awt.Color(2, 104, 66));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 104, 66), 2, true));
        jPanel2.setVerifyInputWhenFocusTarget(false);

        modeloL.setBackground(new java.awt.Color(255, 255, 255));
        modeloL.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        modeloL.setForeground(new java.awt.Color(0, 0, 0));
        modeloL.setText("Modelo");

        marcaL.setBackground(new java.awt.Color(255, 255, 255));
        marcaL.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        marcaL.setForeground(new java.awt.Color(0, 0, 0));
        marcaL.setText("Marca");

        colorL.setBackground(new java.awt.Color(255, 255, 255));
        colorL.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        colorL.setForeground(new java.awt.Color(0, 0, 0));
        colorL.setText("Color");

        motorL.setBackground(new java.awt.Color(255, 255, 255));
        motorL.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        motorL.setForeground(new java.awt.Color(0, 0, 0));
        motorL.setText("Motor");

        patenteL.setBackground(new java.awt.Color(255, 255, 255));
        patenteL.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        patenteL.setForeground(new java.awt.Color(0, 0, 0));
        patenteL.setText("Patente");

        cantPuertasL.setBackground(new java.awt.Color(255, 255, 255));
        cantPuertasL.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cantPuertasL.setForeground(new java.awt.Color(0, 0, 0));
        cantPuertasL.setText("Cant. de Puertas");

        marcaTxt.setBackground(new java.awt.Color(255, 255, 255));
        marcaTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        marcaTxt.setForeground(new java.awt.Color(0, 0, 0));
        marcaTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 104, 66)));

        modeloTxt.setBackground(new java.awt.Color(255, 255, 255));
        modeloTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        modeloTxt.setForeground(new java.awt.Color(0, 0, 0));
        modeloTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 104, 66)));

        colorTxt.setBackground(new java.awt.Color(255, 255, 255));
        colorTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        colorTxt.setForeground(new java.awt.Color(0, 0, 0));
        colorTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 104, 66)));

        motorTxt.setBackground(new java.awt.Color(255, 255, 255));
        motorTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        motorTxt.setForeground(new java.awt.Color(0, 0, 0));
        motorTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 104, 66)));

        patenteTxt.setBackground(new java.awt.Color(255, 255, 255));
        patenteTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        patenteTxt.setForeground(new java.awt.Color(0, 0, 0));
        patenteTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 104, 66)));

        image.setFont(new java.awt.Font("Dialog", 0, 1)); // NOI18N
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\veram\\OneDrive\\Imágenes\\Saved Pictures\\Cohe.jpg")); // NOI18N
        image.setAlignmentY(0.0F);

        CantPuertasCB.setBackground(new java.awt.Color(255, 255, 255));
        CantPuertasCB.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CantPuertasCB.setForeground(new java.awt.Color(0, 0, 0));
        CantPuertasCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4" }));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Agregar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 104, 66)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Limpiar");
        jButton2.setToolTipText("");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 46, 54)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantPuertasL)
                    .addComponent(marcaL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modeloL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(motorL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patenteL, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patenteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantPuertasCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaL)
                    .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloL)
                    .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorL)
                    .addComponent(colorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motorL)
                    .addComponent(motorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patenteL)
                    .addComponent(patenteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantPuertasL)
                    .addComponent(CantPuertasCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    Controladora control = new Controladora();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String modelo = modeloTxt.getText();
        String marca = marcaTxt.getText();
        String motor = motorTxt.getText();
        String color = colorTxt.getText();
        String patente = patenteTxt.getText();
        int cantPuertas = Integer.parseInt((String) CantPuertasCB.getSelectedItem());
        
        control.agregarAuto(marca, modelo, motor, color, patente, cantPuertas);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modeloTxt.setText("");
        marcaTxt.setText("");
        motorTxt.setText("");
        colorTxt.setText("");
        patenteTxt.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CantPuertasCB;
    private javax.swing.JLabel cantPuertasL;
    private javax.swing.JLabel colorL;
    private javax.swing.JTextField colorTxt;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel marcaL;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JLabel modeloL;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JLabel motorL;
    private javax.swing.JTextField motorTxt;
    private javax.swing.JLabel patenteL;
    private javax.swing.JTextField patenteTxt;
    // End of variables declaration//GEN-END:variables
}
