/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.concesionaria.IGU.view;

import com.mycompany.concesionaria.IGU.Principal;
import com.mycompany.concesionaria.Logica.Automovil;
import com.mycompany.concesionaria.Logica.Controladora;

/**
 *
 * @author veram
 */
public class Editar extends javax.swing.JFrame {

    Automovil auto;

    
    public Editar(int idAuto) {
        initComponents();
        this.auto = control.traerAutos(idAuto);
        idTxt.setText(String.valueOf(auto.getId()));
        modeloTxt.setText(auto.getModelo());
        marcaTxt.setText(auto.getMarca());
        motorTxt.setText(auto.getMotor());
        colorTxt.setText(auto.getColor());
        patenteTxt.setText(auto.getPatente());
        CantPuertasCB.setSelectedItem(String.valueOf(auto.getCant_P()));
    }

    Controladora control = new Controladora();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        modeloL = new javax.swing.JLabel();
        marcaL = new javax.swing.JLabel();
        colorL = new javax.swing.JLabel();
        motorL = new javax.swing.JLabel();
        patenteL = new javax.swing.JLabel();
        cantPuertasL = new javax.swing.JLabel();
        marcaTxt = new javax.swing.JTextField();
        modeloTxt = new javax.swing.JTextField();
        colorTxt = new javax.swing.JTextField();
        motorTxt = new javax.swing.JTextField();
        patenteTxt = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        CantPuertasCB = new javax.swing.JComboBox<>();
        guardarBtn = new javax.swing.JButton();
        limpiarBtn = new javax.swing.JButton();
        idL = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        cancelarTxt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Editar Auto");

        jSeparator1.setBackground(new java.awt.Color(2, 104, 66));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 104, 66), 2, true));
        jPanel2.setVerifyInputWhenFocusTarget(false);

        modeloL.setBackground(new java.awt.Color(255, 255, 255));
        modeloL.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        modeloL.setForeground(new java.awt.Color(0, 0, 0));
        modeloL.setText("Modelo");

        marcaL.setBackground(new java.awt.Color(255, 255, 255));
        marcaL.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        marcaL.setForeground(new java.awt.Color(0, 0, 0));
        marcaL.setText("Marca");

        colorL.setBackground(new java.awt.Color(255, 255, 255));
        colorL.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        colorL.setForeground(new java.awt.Color(0, 0, 0));
        colorL.setText("Color");

        motorL.setBackground(new java.awt.Color(255, 255, 255));
        motorL.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        motorL.setForeground(new java.awt.Color(0, 0, 0));
        motorL.setText("Motor");

        patenteL.setBackground(new java.awt.Color(255, 255, 255));
        patenteL.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        patenteL.setForeground(new java.awt.Color(0, 0, 0));
        patenteL.setText("Patente");

        cantPuertasL.setBackground(new java.awt.Color(255, 255, 255));
        cantPuertasL.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cantPuertasL.setForeground(new java.awt.Color(0, 0, 0));
        cantPuertasL.setText("Cant. de Puertas");

        marcaTxt.setBackground(new java.awt.Color(255, 255, 255));
        marcaTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        marcaTxt.setForeground(new java.awt.Color(0, 0, 0));
        marcaTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 104, 66)));

        modeloTxt.setBackground(new java.awt.Color(255, 255, 255));
        modeloTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        modeloTxt.setForeground(new java.awt.Color(0, 0, 0));
        modeloTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 104, 66)));

        colorTxt.setBackground(new java.awt.Color(255, 255, 255));
        colorTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        colorTxt.setForeground(new java.awt.Color(0, 0, 0));
        colorTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 104, 66)));

        motorTxt.setBackground(new java.awt.Color(255, 255, 255));
        motorTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        motorTxt.setForeground(new java.awt.Color(0, 0, 0));
        motorTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 104, 66)));

        patenteTxt.setBackground(new java.awt.Color(255, 255, 255));
        patenteTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        patenteTxt.setForeground(new java.awt.Color(0, 0, 0));
        patenteTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 104, 66)));

        image.setFont(new java.awt.Font("Dialog", 0, 1)); // NOI18N
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\veram\\OneDrive\\Imágenes\\Saved Pictures\\Cohe.jpg")); // NOI18N
        image.setAlignmentY(0.0F);

        CantPuertasCB.setBackground(new java.awt.Color(255, 255, 255));
        CantPuertasCB.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CantPuertasCB.setForeground(new java.awt.Color(0, 0, 0));
        CantPuertasCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4" }));

        guardarBtn.setBackground(new java.awt.Color(153, 255, 153));
        guardarBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        guardarBtn.setForeground(new java.awt.Color(0, 0, 0));
        guardarBtn.setText("Guardar");
        guardarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 104, 66)));
        guardarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarBtn.setFocusPainted(false);
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        limpiarBtn.setBackground(new java.awt.Color(255, 153, 153));
        limpiarBtn.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        limpiarBtn.setForeground(new java.awt.Color(0, 0, 0));
        limpiarBtn.setText("Limpiar");
        limpiarBtn.setToolTipText("");
        limpiarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 46, 54)));
        limpiarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiarBtn.setFocusPainted(false);
        limpiarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarBtnActionPerformed(evt);
            }
        });

        idL.setBackground(new java.awt.Color(255, 255, 255));
        idL.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        idL.setForeground(new java.awt.Color(0, 0, 0));
        idL.setText("Id");

        idTxt.setEditable(false);
        idTxt.setBackground(new java.awt.Color(255, 255, 255));
        idTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        idTxt.setForeground(new java.awt.Color(0, 0, 0));
        idTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 104, 66)));

        cancelarTxt.setBackground(new java.awt.Color(255, 153, 153));
        cancelarTxt.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cancelarTxt.setForeground(new java.awt.Color(0, 0, 0));
        cancelarTxt.setText("Cancelar");
        cancelarTxt.setToolTipText("");
        cancelarTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 46, 54)));
        cancelarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarTxt.setFocusPainted(false);
        cancelarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cantPuertasL)
                        .addComponent(marcaL, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(modeloL, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(colorL, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(motorL, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(patenteL, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(idL))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patenteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantPuertasCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(guardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limpiarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(idL))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaL)
                    .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloL)
                    .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorL)
                    .addComponent(colorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motorL)
                    .addComponent(motorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patenteL)
                    .addComponent(patenteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantPuertasL)
                    .addComponent(CantPuertasCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(limpiarBtn)
                    .addComponent(cancelarTxt)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        
        auto.setMarca(marcaTxt.getText());
        auto.setModelo(modeloTxt.getText());
        auto.setMotor(motorTxt.getText());
        auto.setColor(colorTxt.getText());
        auto.setPatente(patenteTxt.getText());
        auto.setCant_P(Integer.parseInt((String) CantPuertasCB.getSelectedItem()));
        
        control.editarAuto(auto);
        Principal princ = new Principal();
        princ.setVisible(true);
        princ.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void limpiarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBtnActionPerformed
        modeloTxt.setText("");
        marcaTxt.setText("");
        motorTxt.setText("");
        colorTxt.setText("");
        patenteTxt.setText("");
    }//GEN-LAST:event_limpiarBtnActionPerformed

    private void cancelarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarTxtActionPerformed
        Principal princ = new Principal();
        princ.setVisible(true);
        princ.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_cancelarTxtActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CantPuertasCB;
    private javax.swing.JButton cancelarTxt;
    private javax.swing.JLabel cantPuertasL;
    private javax.swing.JLabel colorL;
    private javax.swing.JTextField colorTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel idL;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton limpiarBtn;
    private javax.swing.JLabel marcaL;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JLabel modeloL;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JLabel motorL;
    private javax.swing.JTextField motorTxt;
    private javax.swing.JLabel patenteL;
    private javax.swing.JTextField patenteTxt;
    // End of variables declaration//GEN-END:variables
}
